name: Build LaTeX Document

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Set up LaTeX environment
      run: sudo apt-get install texlive texlive-lang-polish

    - name: Build LaTeX document
      run: pdflatex -interaction=nonstopmode -halt-on-error main.tex

    - name: Rename generated PDF
      run: mv main.pdf "Analiza_Matematyczna_$(date +%Y-%m-%d).pdf"

    - name: Move PDF to pdf directory
      run: mkdir -p pdf && mv "Analiza_Matematyczna_$(date +%Y-%m-%d).pdf" pdf/