name: Download and Commit Artifact

on:
  push:
    branches:
      - master

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: Analiza_Matematyczna_2
          path: ${{ github.workspace }}/pdf

      - name: Move PDF to repository
        run: mv ${{ github.workspace }}/pdf/main.pdf .

      - name: Configure Git
        run: |
          git config --global user.name "AdrianMadajewski"
          git config --global user.email "madajewski.adrian@gmail.com"

      - name: Commit changes
        run: |
          git add main.pdf
          git commit -m "Add PDF artifact"
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}