name: Build, Upload, and Push LaTeX Document

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: Analiza_Matematyczna_2
          path: main.pdf

      - name: Download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: Analiza_Matematyczna_2
          path: ${{ github.workspace }}/pdf

      - name: Move PDF to repository
        run: mv ${{ github.workspace }}/pdf/main.pdf .

      - name: Configure Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"

      - name: Commit and push changes
        run: |
          git add main.pdf
          git commit -m "Update PDF artifact"
          
       # Example of using secrets.GITHUB_TOKEN
      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}